#!/bin/bash
#
#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

# Fetch directory this script is stored in.
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Add repo version of Isabelle to our path.
export PATH="${DIR}/isabelle/bin:$PATH"

# Run the tests from the script directory.
cd ${DIR}
python ./misc/regression/run_tests.py "$@"

