#!/bin/bash

# Copyright 2016, Data61, CSIRO
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ $# -eq 0 ]
then
        available=$(ls $DIR/tokenizer-*)
        echo "Available architectures are:"
        for i in $available
        do
            echo "  ${i#$DIR/tokenizer}"
        done
        exit
fi

executable=$DIR/tokenizer$1
echo "Looking for $executable"

if [ -x $executable ]
then
    :
else
    echo "Unknown architecture $1" >&2
    exit 1
fi
shift

exec $executable "$@"
