/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

/*
 * This file is autogenerated by <kernel>/tools/hardware/outputs/c_header.py.
 */

#pragma once

#define physBase 0x10000000

#ifndef __ASSEMBLER__

#include <config.h>
#include <mode/hardware.h>  /* for KDEV_BASE */
#include <linker.h>         /* for BOOT_RODATA */
#include <basic_types.h>    /* for p_region_t, kernel_frame_t (arch/types.h) */

/* INTERRUPTS */
/* KERNEL_TIMER_IRQ generated from /soc/timer@a00600 */
#define KERNEL_TIMER_IRQ 29
/* KERNEL DEVICES */
#define UART_PPTR (KDEV_BASE + 0x0)
#define GIC_V2_DISTRIBUTOR_PPTR (KDEV_BASE + 0x1000)
#define GIC_V2_CONTROLLER_PPTR (KDEV_BASE + 0x2100)
#define ARM_MP_PRIV_TIMER_PPTR (KDEV_BASE + 0x2600)
#define L2CC_L2C310_PPTR (KDEV_BASE + 0x3000)

static const kernel_frame_t BOOT_RODATA kernel_device_frames[] = {
    #ifdef CONFIG_PRINTING
    /* /soc/aips-bus@2100000/serial@21e8000 */
    {
        .paddr = 0x21e8000,
        .pptr = UART_PPTR,
        .armExecuteNever = true,
        .userAvailable = true
    },
    #endif /* CONFIG_PRINTING */
    /* /soc/interrupt-controller@a01000 */
    {
        .paddr = 0xa01000,
        .pptr = GIC_V2_DISTRIBUTOR_PPTR,
        .armExecuteNever = true,
        .userAvailable = false
    },
    /* /soc/interrupt-controller@a01000, /soc/timer@a00600 */
    {
        .paddr = 0xa00000,
        /* contains GIC_V2_CONTROLLER_PPTR, ARM_MP_PRIV_TIMER_PPTR */
        .pptr = KDEV_BASE + 0x2000,
        .armExecuteNever = true,
        .userAvailable = false
    },
    /* /soc/l2-cache@a02000 */
    {
        .paddr = 0xa02000,
        .pptr = L2CC_L2C310_PPTR,
        .armExecuteNever = true,
        .userAvailable = false
    },
};

/* Elements in kernel_device_frames may be enabled in specific configurations
 * only, but the ARRAY_SIZE() macro will automatically take care of this.
 * However, one corner case remains unsolved where all elements are disabled
 * and this becomes an empty array effectively. Then the C parser used in the
 * formal verification process will fail, because it follows the strict C rules
 * which do not allow empty arrays. Luckily, we have not met this case yet...
 */
#define NUM_KERNEL_DEVICE_FRAMES ARRAY_SIZE(kernel_device_frames)

/* PHYSICAL MEMORY */
static const p_region_t BOOT_RODATA avail_p_regs[] = {
    /* /memory@10000000 */
    {
        .start = 0x10000000,
        .end   = 0x2ff00000
    },
};

#endif /* !__ASSEMBLER__ */
