#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: GPL-2.0-only
#

## Targets
images: SysInit
default: images test
test:
all: images test

#
# Setup heaps.
#

HEAPS += SysInit SysInitExamples

include ../misc/isa-common.mk
