#!/bin/sh
#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: GPL-2.0-only
#

# Running cabal inside `stack exec` fails, because older versions of cabal
# refuse to run with GHC_PACKAGE_PATH set.

unset GHC_PACKAGE_PATH
exec "$@"
