#!/bin/sh
#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

SEM="../StructSupport.thy ./Arrays.thy ./ArraysMemInstance.thy ./CTypes.thy ./CompoundCTypes.thy ./HeapRawState.thy ./Padding.thy ./x86gcc.thy ./x86gcc_typinfo.thy ./CTypesDefs.thy"
UMM=TypHeap.thy
SEP="Sep*.thy"

echo "Sem Defs `grep const $SEM | wc -l` Thms `grep lemma $SEM | wc -l` LoP `cat $SEM | wc -l `"
echo "UMM Defs `grep const $UMM | wc -l` Thms `grep lemma $UMM | wc -l` LoP `cat $UMM | wc -l `"
echo "Sep Defs `grep const $SEP | wc -l` Thms `grep lemma $SEP | wc -l` LoP `cat $SEP | wc -l `"
