#
# Copyright 2018, Data61, CSIRO
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

default: AsmRefineTest

all: AsmRefine AsmRefineTest

report-regression:
	@echo AsmRefine AsmRefineTest

HEAPS += AsmRefine AsmRefineTest

include ../../misc/isa-common.mk
