#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

default: AsmRefineTest

all: AsmRefine AsmRefineTest

HEAPS += AsmRefine AsmRefineTest

include ../../misc/isa-common.mk
